name    'CERNOps-bdii'
version '0.1.0'
author 'schwicke'
license 'Apache License, Version 2.0 (the "License")'
summary 'Resources for managing an EMI bdii service'
description 'This modules provides classes and definitions required to manage and properly configure an EMI bdii service.'
project_page 'https://github.com/cernops/puppet-bdii'
dependency 'puppetlabs/stdlib'
