class bdii::params {
 
  $log_level   = hiera("log_level","DEBUG")
  $port        = hiera("port","2170")
  $user        = hiera("user","ldap")
  $slapdconf   = hiera("slapdconf","/etc/bdii/bdii-slapd.conf")
  $selinux     = hiera("selinux",True)
  $bdiipasswd  = hiera("bdiipasswd",randompass())
  $bdiihost    = hiera("bdiihost","somehost.example.com")

  # site specific stuff:
  $siteurls              =  hiera("siteurls","# DUMMY  ldap://localhost:2170/mds-vo-name=resource,o=grid")
  $sitename              =  hiera("sitename","somesite")      
  $sitebdiihost          =  hiera("sitebdiihost","somehost.example.com") 
  $sitedesc              =  hiera("sitedesc","somesite descr") 
  $siteweb               =  hiera("siteweb","www.somesite.example.com") 
  $sitedistributed       =  hiera("sitedistributed","") 
  $siteloc               =  hiera("siteloc","") 
  $sitecountry           =  hiera("sitecountry","somecountry") 
  $sitelat               =  hiera("sitelat","") 
  $sitelong              =  hiera("sitelong","") 
  $siteemail             =  hiera("siteemail","") 
  $sitesecuritymail      =  hiera("sitesecuritymail","") 
  $sitesupportemail      =  hiera("sitesupportemail","") 
  $config                =  hiera("config","puppet")
  $egeeroc               =  hiera("egeeroc","")
  $egeeservice           =  hiera("egeeservice","prod")
  $grid                  =  hiera("grid","")
  $wlcgtier              =  hiera("wlcgtier","")
}
