class bdii::params {
  # daemon configuration
  $log_level            = hiera('bdii::params::log_level','ERROR')
  $port                 = hiera('bdii::params::port','2170')
  $user                 = hiera('bdii::params::user','ldap')
  $slapdconf            = hiera('bdii::params::slapdconf','/etc/bdii/bdii-slapd.conf')
  $slapdconf_topbdii    = hiera('bdii::params::slapdconf','/etc/bdii/bdii-top-slapd.conf')
  $selinux              = hiera('bdii::params::selinux',false)
  $firewall             = hiera('bdii::params::firewall',true)
  $bdiipasswd           = hiera('bdii::params::bdiipasswd',randompass())
  $bdiihost             = hiera('bdii::params::bdiihost','somehost.example.com')
  # use also bdii::params::delete_delay for compatibility with 1.2.2 module version
  $deletedelay          = hiera('bdii::params::deletedelay', hiera('bdii::params::delete_delay', '0'))
  $deletedelay_topbdii  = hiera('bdii::params::deletedelay', '345600')
  $slapdthreads         = hiera('bdii::params::slapdthreads', '16')
  $slapdthreads_topbdii = hiera('bdii::params::slapdthreads', '64')
  $slapdloglevel        = hiera('bdii::params::slapdloglevel', '0')
  $ramsize              = hiera('bdii::params::ramsize', undef)
  $ramsize_sitebdii     = hiera('bdii::params::ramsize', '500M')
  $ramsize_topbdii      = hiera('bdii::params::ramsize', '2000M')
  # site specific stuff
  $siteurls             = hiera('bdii::params::siteurls',['# DUMMY  ldap://localhost:2170/mds-vo-name=resource,o=grid'])
  $sitename             = hiera('bdii::params::sitename','somesite')
  $sitebdiihost         = hiera('bdii::params::sitebdiihost','somehost.example.com')
  $sitedesc             = hiera('bdii::params::sitedesc','somesite descr')
  $siteweb              = hiera('bdii::params::siteweb','www.somesite.example.com')
  $sitedistributed      = hiera('bdii::params::sitedistributed','')
  $siteloc              = hiera('bdii::params::siteloc','')
  $sitecountry          = hiera('bdii::params::sitecountry','somecountry')
  $sitelat              = hiera('bdii::params::sitelat','')
  $sitelong             = hiera('bdii::params::sitelong','')
  $siteemail            = hiera('bdii::params::siteemail','')
  $sitesecuritymail     = hiera('bdii::params::sitesecuritymail','')
  $sitesupportemail     = hiera('bdii::params::sitesupportemail','')
  $config               = hiera('bdii::params::config','puppet')
  $egeeroc              = hiera('bdii::params::egeeroc','')
  $egeeservice          = hiera('bdii::params::egeeservice','prod')
  $grid                 = hiera('bdii::params::grid',[])
  $wlcgtier             = hiera('bdii::params::wlcgtier','')
  $otherinfo            = hiera('bdii::params::otherinfo',[]) #could be WLCG_PARENT=stuff
  # templates
  $template_config      = hiera('bdii::params::template_config', 'bdii/bdiiconf.erb')
  $template_sysconfig   = hiera('bdii::params::template_sysconfig', 'bdii/bdiisysconf.erb')
  $template_slapd       = hiera('bdii::params::template_config', 'bdii/bdii-slapd.conf.erb')
  $template_slapd_topbdii = hiera('bdii::params::template_config', 'bdii/bdii-top-slapd.conf.erb')
  $template_glite       = hiera('bdii::params::template_glite', 'bdii/glite-info-site-defaults.erb')
  $template_glite_sitebdii = hiera('bdii::params::template_glite', 'bdii/glite-info-site-defaults-site.erb')
  $template_site        = hiera('bdii::params::template_site', 'bdii/site.erb')
  $template_site_urls   = hiera('bdii::params::template_site_urls', 'bdii/site_urls.erb')
}
